name: frontend
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.2
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.20.2
  flex_color_picker: ^3.7.0
  uuid: ^4.5.1
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Medium.otf
        - asset: assets/fonts/Cera-Pro-Bold.otf